services:
  unifi-proxy:
    image: spinogrizz/unifi-proxy:latest
    ports:
      - "${HTTP_PORT:-80}:80"
      # - "${HTTPS_PORT:-443}:443"
    environment:
      - SERVER_NAME=${SERVER_NAME:-unifi.gryzlov.com}
    # volumes:
    #   - ./guide:/var/www/guide:ro
    restart: unless-stopped
